# .goreleaser.yml
# Build customization
builds:
  - main: main.go
    binary: auto-release
    ldflags: -s -w -X main.Version={{.Version}} -X main.CommitHash={{.Commit}} -X main.CompileDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
# Archive customization
archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    386: i386
    amd64: x86_64
    darwin: macos
  files:
    - LICENSE*
    - README*
# Homebrew customization
brew:
  github:
    owner: dotzero
    name: homebrew-tap
  commit_author:
    name: dotzero
    email: mail@dotzero.ru
  folder: Formula
  homepage: https://github.com/dotzero/git-profile
  description: Allows to add and switch between multiple user profiles in your git repositories
  test: |
    system "#{bin}/git-profile version"
